# Problem 1

In [2]:
import numpy as np

In [55]:
def power_matrix(inp_vac,n,ascending=False):
    if ascending:
        power_mat = np.array([x**(i) for x in inp_vac for i in range(n)]).reshape(len(inp_vac),n)
    else:
        power_mat = np.array([x**(n-1-i) for x in inp_vac for i in range(n)]).reshape(len(inp_vac),n)
    return power_mat

inp_vac = np.array([1,2,3,4,5])
col  = 5

print('Input array is : ',inp_vac,"\n")
print('Number of columns in output matrix : ',max_pow,"\n")
print("---Ascending power matrix---\n")
print(power_matrix(inp_vac,col,True),"\n")
print("---Dscending power matrix---\n")
print(power_matrix(inp_vac,col))

Input array is :  [1 2 3 4 5] 

Number of columns in output matrix :  5 

---Ascending power matrix---

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]] 

---Dscending power matrix---

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


# Problem 2

In [112]:
mat = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window_size = 3

In [128]:
def moving_avgerage(input_mat,k):

    n=0
    sub_arrays = []
    moving_avg = []

    for i in range(len(mat)-k+1):
        sub_array = np.array([mat[i] for i in range(n,n+k)])
        sub_arrays.append(sub_array)
        mean_of_sub_array = np.array([mat[i] for i in range(n,n+k)]).mean()
        moving_avg.append(np.round(mean_of_sub_array,2))
        n=n+1

    return sub_arrays,moving_avg

arr,avg = moving_avgerage(mat,window_size) 

print("-----The moving averages with window size (k={}) of a array sequence (n={}) is shown below-----\n".format(window_size,len(mat)))
for x in range(len(mat)-window_size+1): 
    print("Sub array is {} and average is = {} \n".format(arr[x],avg[x]))

-----The moving averages with window size (k=3) of a array sequence (n=13) is shown below-----

Sub array is [3 5 7] and average is = 5.0 

Sub array is [5 7 2] and average is = 4.67 

Sub array is [7 2 8] and average is = 5.67 

Sub array is [ 2  8 10] and average is = 6.67 

Sub array is [ 8 10 11] and average is = 9.67 

Sub array is [10 11 65] and average is = 28.67 

Sub array is [11 65 72] and average is = 49.33 

Sub array is [65 72 81] and average is = 72.67 

Sub array is [72 81 99] and average is = 84.0 

Sub array is [ 81  99 100] and average is = 93.33 

Sub array is [ 99 100 150] and average is = 116.33 

